# Generated by Django 6.1.1 on 2026-09-21 18:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CompanyProfile",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("legal_name", models.CharField(max_length=255)),
                ("address_line_1", models.CharField(blank=True, max_length=255)),
                ("address_line_2", models.CharField(blank=True, max_length=255)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                ("city", models.CharField(blank=True, max_length=100)),
                (
                    "country_code",
                    models.CharField(
                        default="DE",
                        max_length=2,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z]{2}$", "Use an ISO 3166-1 alpha-2 code."
                            )
                        ],
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("tax_number", models.CharField(blank=True, max_length=50)),
                ("vat_identifier", models.CharField(blank=True, max_length=50)),
                ("company_identifier", models.CharField(blank=True, max_length=100)),
                ("bank_account_holder", models.CharField(blank=True, max_length=255)),
                ("iban", models.CharField(blank=True, max_length=34)),
                ("bic", models.CharField(blank=True, max_length=11)),
                ("payment_instructions", models.TextField(blank=True)),
                (
                    "default_currency",
                    models.CharField(choices=[("EUR", "Euro")], default="EUR", max_length=3),
                ),
                (
                    "default_locale",
                    models.CharField(
                        choices=[
                            ("en-DE", "English (Germany)"),
                            ("de-DE", "German (Germany)"),
                        ],
                        default="de-DE",
                        max_length=5,
                    ),
                ),
                (
                    "default_ui_language",
                    models.CharField(
                        choices=[("en", "English"), ("de", "German")],
                        default="de",
                        max_length=2,
                    ),
                ),
                (
                    "default_document_language",
                    models.CharField(
                        choices=[("en", "English"), ("de", "German")],
                        default="de",
                        max_length=2,
                    ),
                ),
                (
                    "invoice_number_prefix",
                    models.CharField(default="RE-", max_length=30),
                ),
                (
                    "invoice_number_next",
                    models.PositiveBigIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "invoice_number_padding",
                    models.PositiveSmallIntegerField(
                        default=4,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                    ),
                ),
                (
                    "invoice_number_reset",
                    models.CharField(
                        choices=[("never", "Never"), ("annual", "Annually")],
                        default="annual",
                        max_length=10,
                    ),
                ),
                ("feature_payment_requests", models.BooleanField(default=False)),
                ("feature_reminders", models.BooleanField(default=False)),
                ("feature_time_tracking", models.BooleanField(default=False)),
                ("modified_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "company profile",
            },
        ),
    ]
