# Generated by Django 6.1.1 on 2026-09-22 08:55

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("configuration", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaxProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=80)),
                ("version", models.PositiveSmallIntegerField(default=1)),
                ("name", models.CharField(max_length=120)),
                (
                    "tax_category",
                    models.CharField(
                        choices=[("S", "Standard rated"), ("E", "Exempt")], max_length=1
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                    ),
                ),
                ("exemption_reason_code", models.CharField(blank=True, max_length=50)),
                ("exemption_wording_en", models.CharField(blank=True, max_length=255)),
                ("exemption_wording_de", models.CharField(blank=True, max_length=255)),
                (
                    "price_entry_policy",
                    models.CharField(choices=[("net", "Net"), ("gross", "Gross")], max_length=5),
                ),
                (
                    "tax_column_policy",
                    models.CharField(choices=[("show", "Show"), ("hide", "Hide")], max_length=4),
                ),
                ("requires_tax_number", models.BooleanField(default=False)),
                ("requires_vat_identifier", models.BooleanField(default=False)),
                ("is_default", models.BooleanField(default=False)),
                ("is_current", models.BooleanField(default=True)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("code", "-version"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("code", "version"), name="unique_tax_profile_version"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_current", True)),
                        fields=("code",),
                        name="unique_current_tax_profile_code",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_current", True), ("is_default", True)),
                        fields=("is_default",),
                        name="one_current_default_tax_profile",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("requires_tax_number", True),
                            ("requires_vat_identifier", True),
                            _connector="OR",
                        ),
                        name="tax_profile_requires_seller_identifier",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("exemption_reason_code", ""),
                                ("exemption_wording_de", ""),
                                ("exemption_wording_en", ""),
                                ("rate__gt", 0),
                                ("tax_category", "S"),
                            ),
                            models.Q(
                                ("rate", 0),
                                ("tax_category", "E"),
                                models.Q(("exemption_reason_code", ""), _negated=True),
                                models.Q(("exemption_wording_en", ""), _negated=True),
                                models.Q(("exemption_wording_de", ""), _negated=True),
                            ),
                            _connector="OR",
                        ),
                        name="supported_german_tax_profile",
                    ),
                ],
            },
        ),
    ]
