# Generated by Django 6.1.1 on 2026-09-23 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("configuration", "0002_taxprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyprofile",
            name="invoice_number_year",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
