# Generated by Django 6.1.1 on 2026-09-22 17:27

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("configuration", "0002_taxprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="CatalogItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z][A-Z0-9_-]*$",
                                "Use an uppercase language-neutral code containing letters, numbers, _ or -.",
                            )
                        ],
                    ),
                ),
                ("description_en", models.CharField(max_length=255)),
                ("description_de", models.CharField(max_length=255)),
                (
                    "unit",
                    models.CharField(
                        choices=[("C62", "Piece"), ("HUR", "Hour"), ("DAY", "Day")],
                        max_length=3,
                    ),
                ),
                (
                    "default_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "minimum_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "maximum_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                ("is_archived", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "default_tax_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="catalog_items",
                        to="configuration.taxprofile",
                    ),
                ),
            ],
            options={
                "ordering": ("code",),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("default_price__gte", 0)),
                        name="catalog_default_price_nonnegative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("minimum_price__isnull", True),
                            ("minimum_price__gte", 0),
                            _connector="OR",
                        ),
                        name="catalog_minimum_price_nonnegative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("maximum_price__isnull", True),
                            ("maximum_price__gte", 0),
                            _connector="OR",
                        ),
                        name="catalog_maximum_price_nonnegative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("minimum_price__isnull", True),
                            ("default_price__gte", models.F("minimum_price")),
                            _connector="OR",
                        ),
                        name="catalog_default_at_or_above_minimum",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("maximum_price__isnull", True),
                            ("default_price__lte", models.F("maximum_price")),
                            _connector="OR",
                        ),
                        name="catalog_default_at_or_below_maximum",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("minimum_price__isnull", True),
                            ("maximum_price__isnull", True),
                            ("minimum_price__lte", models.F("maximum_price")),
                            _connector="OR",
                        ),
                        name="catalog_advisory_price_order",
                    ),
                ],
            },
        ),
    ]
