# Generated by Django 6.1.1 on 2026-09-22 17:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
        ("configuration", "0002_taxprofile"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="catalogitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("description_en", ""), _negated=True),
                name="catalog_english_description_required",
            ),
        ),
        migrations.AddConstraint(
            model_name="catalogitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("description_de", ""), _negated=True),
                name="catalog_german_description_required",
            ),
        ),
        migrations.AddConstraint(
            model_name="catalogitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("unit__in", ["C62", "HUR", "DAY"])),
                name="catalog_supported_unit",
            ),
        ),
    ]
