# Generated by Django 6.1.1 on 2026-09-22 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_catalogitem_catalog_english_description_required_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="catalogitem",
            name="custom_data",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
