# Generated by Django 6.1.1 on 2026-09-22 20:16

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_catalogitem_custom_data"),
        ("configuration", "0002_taxprofile"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="catalogitem",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["custom_data"], name="catalog_custom_data_gin"
            ),
        ),
    ]
