# Generated by Django 6.1.1 on 2026-09-23 08:32

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("customers", "0003_customer_customer_custom_data_gin"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_type",
                    models.CharField(
                        choices=[("STANDARD", "Standard")],
                        default="STANDARD",
                        max_length=20,
                    ),
                ),
                (
                    "lifecycle_status",
                    models.CharField(choices=[("DRAFT", "Draft")], default="DRAFT", max_length=20),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[("UNPAID", "Unpaid"), ("PAID", "Paid")],
                        default="UNPAID",
                        max_length=20,
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(blank=True, max_length=80, null=True, unique=True),
                ),
                ("currency", models.CharField(default="EUR", max_length=3)),
                (
                    "document_language",
                    models.CharField(choices=[("en", "English"), ("de", "German")], max_length=2),
                ),
                ("issue_date", models.DateField()),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14),
                ),
                (
                    "tax_total",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14),
                ),
                (
                    "grand_total",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-pk"),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("lifecycle_status", "DRAFT")),
                        name="invoice_supported_lifecycle",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("invoice_type", "STANDARD")),
                        name="invoice_supported_type",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("payment_status__in", ("UNPAID", "PAID"))),
                        name="invoice_payment_state",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("invoice_number__isnull", True)),
                        name="draft_has_no_number",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("grand_total__gte", 0),
                            ("subtotal__gte", 0),
                            ("tax_total__gte", 0),
                        ),
                        name="invoice_nonnegative_totals",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("version__gte", 1)),
                        name="invoice_positive_version",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("document_language__in", ("en", "de"))),
                        name="invoice_supported_language",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("currency", "EUR")),
                        name="invoice_supported_currency",
                    ),
                ],
            },
        ),
    ]
