# Generated by Django 6.1.1 on 2026-09-23 09:51

from decimal import Decimal

import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0001_initial"),
        ("customers", "0003_customer_customer_custom_data_gin"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoiceLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                ("service_date", models.DateField(blank=True, null=True)),
                ("service_period_end", models.DateField(blank=True, null=True)),
                ("item_code", models.CharField(blank=True, max_length=50)),
                ("description", models.CharField(max_length=255)),
                ("unit", models.CharField(max_length=3)),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=12)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "discount_percent",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=5),
                ),
                ("tax_category", models.CharField(max_length=1)),
                ("tax_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                ("price_entry_policy", models.CharField(max_length=5)),
                ("exemption_reason_code", models.CharField(blank=True, max_length=50)),
                ("exemption_wording", models.CharField(blank=True, max_length=255)),
                (
                    "net_total",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14),
                ),
                (
                    "tax_total",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14),
                ),
                (
                    "gross_total",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14),
                ),
            ],
            options={
                "ordering": ("position", "pk"),
            },
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "grand_total",
                        django.db.models.expressions.CombinedExpression(
                            models.F("subtotal"), "+", models.F("tax_total")
                        ),
                    )
                ),
                name="invoice_totals_consistent",
            ),
        ),
        migrations.AddField(
            model_name="invoiceline",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="billing.invoice",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoiceline",
            constraint=models.UniqueConstraint(
                fields=("invoice", "position"), name="unique_invoice_line_position"
            ),
        ),
        migrations.AddConstraint(
            model_name="invoiceline",
            constraint=models.CheckConstraint(
                condition=models.Q(("position__gte", 1)),
                name="invoice_line_positive_position",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoiceline",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)),
                name="invoice_line_positive_quantity",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoiceline",
            constraint=models.CheckConstraint(
                condition=models.Q(("unit_price__gte", 0)),
                name="invoice_line_nonnegative_price",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoiceline",
            constraint=models.CheckConstraint(
                condition=models.Q(("discount_percent__gte", 0), ("discount_percent__lte", 100)),
                name="invoice_line_discount_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoiceline",
            constraint=models.CheckConstraint(
                condition=models.Q(("tax_rate__gte", 0), ("tax_rate__lte", 100)),
                name="invoice_line_rate_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoiceline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("exemption_reason_code", ""),
                        ("exemption_wording", ""),
                        ("tax_category", "S"),
                        ("tax_rate__gt", 0),
                    ),
                    models.Q(
                        ("tax_category", "E"),
                        ("tax_rate", 0),
                        models.Q(("exemption_reason_code", ""), _negated=True),
                        models.Q(("exemption_wording", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="invoice_line_tax_semantics",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoiceline",
            constraint=models.CheckConstraint(
                condition=models.Q(("price_entry_policy__in", ("net", "gross"))),
                name="invoice_line_price_policy",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoiceline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("gross_total__gte", 0),
                    ("net_total__gte", 0),
                    ("tax_total__gte", 0),
                ),
                name="invoice_line_nonnegative_totals",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoiceline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "gross_total",
                        django.db.models.expressions.CombinedExpression(
                            models.F("net_total"), "+", models.F("tax_total")
                        ),
                    )
                ),
                name="invoice_line_totals_consistent",
            ),
        ),
    ]
