# Generated by Django 6.1.1 on 2026-09-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0002_invoiceline_invoice_invoice_totals_consistent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="recipient",
            field=models.JSONField(default=dict),
        ),
    ]
