# Generated by Django 6.1.1 on 2026-09-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0003_invoice_recipient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="recipient",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
