# Generated by Django 6.1.1 on 2026-09-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0004_alter_invoice_recipient"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoicePreset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("lines", models.JSONField(default=list)),
                ("is_archived", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("name", "pk"),
            },
        ),
    ]
