# Generated by Django 6.1.1 on 2026-09-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0005_invoicepreset"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="custom_data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="invoiceline",
            name="custom_data",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
