# Generated by Django 6.1.1 on 2026-09-23 15:14

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0006_invoice_custom_data_invoiceline_custom_data"),
        ("customers", "0003_customer_customer_custom_data_gin"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="invoice",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["custom_data"], name="invoice_custom_data_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="invoiceline",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["custom_data"], name="invoice_line_custom_gin"
            ),
        ),
    ]
