# Generated by Django 6.1.1 on 2026-09-23 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0007_invoice_invoice_custom_data_gin_and_more"),
        ("customers", "0003_customer_customer_custom_data_gin"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="invoice",
            name="invoice_supported_lifecycle",
        ),
        migrations.RemoveConstraint(
            model_name="invoice",
            name="draft_has_no_number",
        ),
        migrations.AddField(
            model_name="invoice",
            name="issuance_key",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="invoice",
            name="snapshot",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="lifecycle_status",
            field=models.CharField(
                choices=[("DRAFT", "Draft"), ("ISSUING", "Issuing")],
                default="DRAFT",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(("lifecycle_status__in", ("DRAFT", "ISSUING"))),
                name="invoice_supported_lifecycle",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("invoice_number__isnull", True),
                        ("issuance_key", ""),
                        ("lifecycle_status", "DRAFT"),
                        ("snapshot__isnull", True),
                    ),
                    models.Q(
                        ("invoice_number__isnull", False),
                        ("lifecycle_status", "ISSUING"),
                        ("snapshot__isnull", False),
                        models.Q(("issuance_key", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="invoice_number_matches_lifecycle",
            ),
        ),
    ]
