# Generated by Django 6.1.1 on 2026-09-22 19:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomFieldDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[a-z][a-z0-9_]*$", "Use a lowercase machine key."
                            )
                        ],
                    ),
                ),
                (
                    "target",
                    models.CharField(
                        choices=[
                            ("customer", "Customer"),
                            ("catalog_item", "Catalog item"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("long_text", "Long text"),
                            ("integer", "Integer"),
                            ("decimal", "Decimal"),
                            ("boolean", "Boolean"),
                            ("date", "Date"),
                            ("choice", "Choice"),
                        ],
                        max_length=20,
                    ),
                ),
                ("label_en", models.CharField(max_length=120)),
                ("label_de", models.CharField(max_length=120)),
                ("help_en", models.CharField(blank=True, max_length=255)),
                ("help_de", models.CharField(blank=True, max_length=255)),
                ("required", models.BooleanField(default=False)),
                ("default_value", models.JSONField(blank=True, null=True)),
                ("choices", models.JSONField(blank=True, default=list)),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "visibility",
                    models.CharField(
                        choices=[("internal", "Internal"), ("document", "Document")],
                        default="internal",
                        max_length=20,
                    ),
                ),
                (
                    "search_mode",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("exact", "Exact"),
                            ("range", "Range"),
                            ("text", "Text"),
                        ],
                        default="none",
                        max_length=10,
                    ),
                ),
                ("is_sensitive", models.BooleanField(default=False)),
                ("is_retired", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ("target", "display_order", "key"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("target", "key"), name="unique_custom_field_target_key"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("target__in", ["customer", "catalog_item"])),
                        name="custom_field_target",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "data_type__in",
                                [
                                    "text",
                                    "long_text",
                                    "integer",
                                    "decimal",
                                    "boolean",
                                    "date",
                                    "choice",
                                ],
                            )
                        ),
                        name="custom_field_type",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("search_mode__in", ["none", "exact", "range", "text"])),
                        name="custom_field_search",
                    ),
                ],
            },
        ),
    ]
