# Generated by Django 6.1.1 on 2026-09-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custom_fields", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="customfielddefinition",
            name="custom_field_target",
        ),
        migrations.AlterField(
            model_name="customfielddefinition",
            name="target",
            field=models.CharField(
                choices=[
                    ("customer", "Customer"),
                    ("catalog_item", "Catalog item"),
                    ("invoice", "Invoice"),
                    ("invoice_line", "Invoice line"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="customfielddefinition",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "target__in",
                        ["customer", "catalog_item", "invoice", "invoice_line"],
                    )
                ),
                name="custom_field_target",
            ),
        ),
    ]
