# Generated by Django 6.1.1 on 2026-09-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documenttemplateversion",
            name="asset_keys",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="documenttemplateversion",
            name="page_settings",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
