# Generated by Django 6.1.1 on 2026-09-22 14:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "party_type",
                    models.CharField(
                        choices=[
                            ("person", "Person"),
                            ("organization", "Organization"),
                        ],
                        max_length=20,
                    ),
                ),
                ("given_name", models.CharField(blank=True, max_length=120)),
                ("family_name", models.CharField(blank=True, max_length=120)),
                ("organization_name", models.CharField(blank=True, max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("customer_number", models.CharField(max_length=50, unique=True)),
                (
                    "preferred_language",
                    models.CharField(
                        choices=[("en", "English"), ("de", "German")],
                        default="de",
                        max_length=2,
                    ),
                ),
                ("is_archived", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("customer_number",),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("family_name__gt", ""),
                                ("given_name__gt", ""),
                                ("organization_name", ""),
                                ("party_type", "person"),
                            ),
                            models.Q(
                                ("organization_name__gt", ""),
                                ("party_type", "organization"),
                                ("family_name", ""),
                                ("given_name", ""),
                            ),
                            _connector="OR",
                        ),
                        name="customer_party_fields_match_type",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="BillingRecipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "party_type",
                    models.CharField(
                        choices=[
                            ("person", "Person"),
                            ("organization", "Organization"),
                        ],
                        max_length=20,
                    ),
                ),
                ("given_name", models.CharField(blank=True, max_length=120)),
                ("family_name", models.CharField(blank=True, max_length=120)),
                ("organization_name", models.CharField(blank=True, max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("address_line_1", models.CharField(blank=True, max_length=255)),
                ("address_line_2", models.CharField(blank=True, max_length=255)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                ("city", models.CharField(blank=True, max_length=100)),
                (
                    "country_code",
                    models.CharField(
                        default="DE",
                        max_length=2,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z]{2}$", "Use an ISO 3166-1 alpha-2 code."
                            )
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_recipients",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "ordering": ("pk",),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("family_name__gt", ""),
                                ("given_name__gt", ""),
                                ("organization_name", ""),
                                ("party_type", "person"),
                            ),
                            models.Q(
                                ("organization_name__gt", ""),
                                ("party_type", "organization"),
                                ("family_name", ""),
                                ("given_name", ""),
                            ),
                            _connector="OR",
                        ),
                        name="billing_recipient_party_fields_match_type",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CustomerAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=80)),
                ("address_line_1", models.CharField(blank=True, max_length=255)),
                ("address_line_2", models.CharField(blank=True, max_length=255)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                ("city", models.CharField(blank=True, max_length=100)),
                (
                    "country_code",
                    models.CharField(
                        default="DE",
                        max_length=2,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z]{2}$", "Use an ISO 3166-1 alpha-2 code."
                            )
                        ],
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "ordering": ("pk",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("customer", "label"),
                        name="unique_customer_address_label",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_primary", True)),
                        fields=("customer",),
                        name="one_primary_address_per_customer",
                    ),
                ],
            },
        ),
    ]
