# Generated by Django 6.1.1 on 2026-09-22 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="custom_data",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
