# Generated by Django 6.1.1 on 2026-09-22 20:16

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0002_customer_custom_data"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="customer",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["custom_data"], name="customer_custom_data_gin"
            ),
        ),
    ]
