# Generated by Django 6.1.1 on 2026-09-23 17:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WorkItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_type", models.CharField(max_length=100)),
                ("identity", models.CharField(max_length=255)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                ("max_attempts", models.PositiveSmallIntegerField(default=5)),
                ("lease_until", models.DateTimeField(blank=True, null=True)),
                (
                    "lease_token",
                    models.UUIDField(blank=True, editable=False, null=True),
                ),
                ("failure_code", models.CharField(blank=True, max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [models.Index(fields=["state", "scheduled_at"], name="work_ready_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("job_type", "identity"), name="work_unique_identity"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("max_attempts__gte", 1)),
                        name="work_positive_max_attempts",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("attempt_count__lte", models.F("max_attempts"))),
                        name="work_attempts_bounded",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("lease_token__isnull", False),
                                ("lease_until__isnull", False),
                                ("state", "running"),
                            ),
                            models.Q(
                                ("lease_token__isnull", False),
                                ("lease_until__isnull", False),
                                ("state", "running"),
                                _negated=True,
                            ),
                            _connector="OR",
                        ),
                        name="work_running_has_lease",
                    ),
                ],
            },
        ),
    ]
