# Generated by Django 6.1.1 on 2026-09-23 17:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workers", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="workitem",
            name="work_running_has_lease",
        ),
        migrations.AddConstraint(
            model_name="workitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("lease_token__isnull", False),
                        ("lease_until__isnull", False),
                        ("state", "running"),
                    ),
                    models.Q(
                        ("lease_token__isnull", True),
                        ("lease_until__isnull", True),
                        ("state__in", ["queued", "succeeded", "failed"]),
                    ),
                    _connector="OR",
                ),
                name="work_running_has_lease",
            ),
        ),
    ]
